# DO NOT EDIT THIS FILE!
#
# Python module ChatApp generated by omniidl

import omniORB
omniORB.updateModule("ChatApp")

# ** 1. Stub files contributing to this module
import chat_idl

# ** 2. Sub-modules

# ** 3. End
