# Python stubs generated by omniidl from chat.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "ChatApp"
#
__name__ = "ChatApp"
_0_ChatApp = omniORB.openModule("ChatApp", r"chat.idl")
_0_ChatApp__POA = omniORB.openModule("ChatApp__POA", r"chat.idl")


# interface ChatServer
_0_ChatApp._d_ChatServer = (omniORB.tcInternal.tv_objref, "IDL:ChatApp/ChatServer:1.0", "ChatServer")
omniORB.typeMapping["IDL:ChatApp/ChatServer:1.0"] = _0_ChatApp._d_ChatServer
_0_ChatApp.ChatServer = omniORB.newEmptyClass()
class ChatServer :
    _NP_RepositoryId = _0_ChatApp._d_ChatServer[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_ChatApp.ChatServer = ChatServer
_0_ChatApp._tc_ChatServer = omniORB.tcInternal.createTypeCode(_0_ChatApp._d_ChatServer)
omniORB.registerType(ChatServer._NP_RepositoryId, _0_ChatApp._d_ChatServer, _0_ChatApp._tc_ChatServer)

# ChatServer operations and attributes
ChatServer._d_sendMessage = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), None)
ChatServer._d_receiveMessage = ((), ((omniORB.tcInternal.tv_string,0), ), None)

# ChatServer object reference
class _objref_ChatServer (CORBA.Object):
    _NP_RepositoryId = ChatServer._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def sendMessage(self, *args):
        return self._obj.invoke("sendMessage", _0_ChatApp.ChatServer._d_sendMessage, args)

    def receiveMessage(self, *args):
        return self._obj.invoke("receiveMessage", _0_ChatApp.ChatServer._d_receiveMessage, args)

omniORB.registerObjref(ChatServer._NP_RepositoryId, _objref_ChatServer)
_0_ChatApp._objref_ChatServer = _objref_ChatServer
del ChatServer, _objref_ChatServer

# ChatServer skeleton
__name__ = "ChatApp__POA"
class ChatServer (PortableServer.Servant):
    _NP_RepositoryId = _0_ChatApp.ChatServer._NP_RepositoryId


    _omni_op_d = {"sendMessage": _0_ChatApp.ChatServer._d_sendMessage, "receiveMessage": _0_ChatApp.ChatServer._d_receiveMessage}

ChatServer._omni_skeleton = ChatServer
_0_ChatApp__POA.ChatServer = ChatServer
omniORB.registerSkeleton(ChatServer._NP_RepositoryId, ChatServer)
del ChatServer
__name__ = "ChatApp"

# interface ChatClient
_0_ChatApp._d_ChatClient = (omniORB.tcInternal.tv_objref, "IDL:ChatApp/ChatClient:1.0", "ChatClient")
omniORB.typeMapping["IDL:ChatApp/ChatClient:1.0"] = _0_ChatApp._d_ChatClient
_0_ChatApp.ChatClient = omniORB.newEmptyClass()
class ChatClient :
    _NP_RepositoryId = _0_ChatApp._d_ChatClient[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_ChatApp.ChatClient = ChatClient
_0_ChatApp._tc_ChatClient = omniORB.tcInternal.createTypeCode(_0_ChatApp._d_ChatClient)
omniORB.registerType(ChatClient._NP_RepositoryId, _0_ChatApp._d_ChatClient, _0_ChatApp._tc_ChatClient)

# ChatClient operations and attributes
ChatClient._d_receiveMessage = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), None)

# ChatClient object reference
class _objref_ChatClient (CORBA.Object):
    _NP_RepositoryId = ChatClient._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def receiveMessage(self, *args):
        return self._obj.invoke("receiveMessage", _0_ChatApp.ChatClient._d_receiveMessage, args)

omniORB.registerObjref(ChatClient._NP_RepositoryId, _objref_ChatClient)
_0_ChatApp._objref_ChatClient = _objref_ChatClient
del ChatClient, _objref_ChatClient

# ChatClient skeleton
__name__ = "ChatApp__POA"
class ChatClient (PortableServer.Servant):
    _NP_RepositoryId = _0_ChatApp.ChatClient._NP_RepositoryId


    _omni_op_d = {"receiveMessage": _0_ChatApp.ChatClient._d_receiveMessage}

ChatClient._omni_skeleton = ChatClient
_0_ChatApp__POA.ChatClient = ChatClient
omniORB.registerSkeleton(ChatClient._NP_RepositoryId, ChatClient)
del ChatClient
__name__ = "ChatApp"

#
# End of module "ChatApp"
#
__name__ = "chat_idl"

_exported_modules = ( "ChatApp", )

# The end.
